Repository acikkaynak/ben-yaparim, pull requests merged in 2023-02, with the labels that each got.

#20 Feature/send approval mail
  src/components/Collapse/index.js
  src/firebase/calls.js
  src/firebase/mail.js
  src/pages/[id].js
Labels: enhancement

#25 Feature/name change
  package-lock.json
  package.json
  src/pages/index.js
Labels: documentation

#31 Fix/apply button non signed users
  src/pages/[id].js
Labels: bug

#46 Clear call state after creating call
  src/pages/stk/open-call.js
Labels: bug

#48 fix/application-button
  src/components/Card/index.js
Labels: bug

#57 fix/selectbox
  src/pages/profile.js
  src/pages/register.js
  src/pages/stk/open-call.js
  src/pages/stk/profile.js
Labels: bug

#70 bug/detail-update
  src/firebase/calls.js
  src/pages/[id].js
Labels: bug, confirmed

#72 bug/typo
  src/pages/register.js
Labels: bug, confirmed

#71 fix/login-page
  src/components/Navbar/index.js
  src/pages/login.js
  src/pages/profile.js
  src/pages/register.js
Labels: bug

#74 feature/collapse-status
  src/components/Collapse/index.js
  src/firebase/users.js
  src/pages/[id].js
Labels: enhancement

#63 Feature/prevent call overlap
  src/firebase/users.js
  src/pages/[id].js
  src/pages/profile.js
  src/pages/stk/profile.js
Labels: enhancement

#84 Feature/close calls
  src/firebase/calls.js
  src/pages/[id].js
  src/pages/index.js
  src/pages/profile.js
  src/pages/stk/open-call.js
  src/pages/stk/profile.js
Labels: enhancement

#83 fix/skills-overflow
  src/components/Card/index.js
  src/components/Tags/color-tag.js
Labels: bug, confirmed

#86 call link retrieval changed
  src/components/Share/share.js
Labels: bug

#87 feat/revoke-application
  src/firebase/users.js
  src/pages/[id].js
  src/pages/index.js
Labels: enhancement, confirmed

#76 Feature/required fields
  package-lock.json
  package.json
  public/images/logo.png
  src/components/Collapse/index.js
  src/firebase/calls.js
  src/pages/[id].js
  src/pages/index.js
  src/pages/login.js
  src/pages/profile.js
  src/pages/register.js
  src/pages/stk/open-call.js
  src/pages/stk/profile.js
Labels: enhancement
